# Generated by Django 3.2.7 on 2025-01-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_auto_20250131_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='score',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
