# Generated by Django 3.2.7 on 2025-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0006_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='victories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='win_rate',
            field=models.IntegerField(default=0),
        ),
    ]
