# Generated by Django 3.2.7 on 2025-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_auto_20250201_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
