# Generated by Django 5.1.4 on 2025-01-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
