# Generated by Django 5.1.4 on 2025-01-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0002_alter_friendrequest_unique_together'),
        ('UserAccount', '0002_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='UserAccount.userprofile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='UserAccount.userprofile'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
